#!/usr/bin/env bash
# This script displays the PID and full path process name of processes containing "bash".

pgrep -a bash | while read -r line; do
  pid=$(echo "$line" | awk '{print $1}')
  command=$(echo "$line" | awk '{$1=""; print $0}')
  if [[ "$command" == *"bash"* ]]; then
    printf "%s%s\n" "$pid" "$command"
  fi
done
