#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, handles SIGTERM, and displays "I am invincible!!!".

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
