#!/usr/bin/env bash
# This script displays the username, user id, and home directory path from the /etc/passwd file

while IFS=: read -r username _ uid _ _ homedir _; do
  echo "$username:$uid:$homedir"
done < /etc/passwd
