#!/usr/bin/env bash
# This script displays specific messages for the 4th and 8th iterations, and "Best School" for others

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]
  then
    echo "bad luck"
  elif [ $counter -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((counter++))
done
