#!/usr/bin/env bash
# Configures localhost to 127.0.0.2 and facebook.com to 8.8.8.8, with direct file writing.

# Clear the /etc/hosts file, then write the needed lines
sudo truncate -s 0 /etc/hosts
echo "" | sudo tee -a /etc/hosts
echo "" | sudo tee -a /etc/hosts
